#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias subl='/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl'
alias term='itermocil'
alias pyserver='python -m SimpleHTTPServer 9000'
alias weather='curl -4 wttr.in/Atlanta'
alias v='vim .'
alias yolo='git push origin master && git push heroku master'
alias dot='~/.dotfiles'
alias desk='~/Desktop'
alias del='rm -rf'
alias html='atom . && open index.html'
alias newhtml='mkdir css js && touch index.html css/style.css js/main.js'
alias npmgrade='npm install && atom .'
alias npmsetup='mkdir public public/css views && touch app.js public/css/style.css && npm init && npm install express nodemon --save && atom .'
alias npmpack='npm install mustache mustache-express body-parser express-validator express-session --save'
alias npmall='npmsetup && npmpack'
alias runreact='./bin/webpack-dev-server'


# Git Shortcuts
alias gp="git push"
alias gc="git commit"
alias ga="git add ."
alias gs="git status"

# Waiting Dots
COMPLETION_WAITING_DOTS="true"

# The Rubies
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Iron Yard Specific Stuff
alias iron='~/Documents/fullStack'
alias sb='~/Projects/Sandbox/playground'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
